version: 2.1
orbs:
    cypress: cypress-io/cypress@1
    node: circleci/node@1.1.6
jobs:
    build:
        executor:
            name: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run:
                            name: Install
                            command: npm install
                      - run:
                            name: Build
                            command: npm run build:ci
                      - run:
                            name: Start live server
                            command: npm run start:ci
                            background: true
workflows:
    build-and-test:
        jobs:
            - cypress/install:
                  build: npm run build:ci
            - cypress/run:
                  start: npm run start:ci
